vich_uploader:
    db_driver: orm

    mappings:
        image_file:
            uri_prefix: '%app.path.image_file%'
            upload_destination: '%kernel.project_dir%/public%app.path.image_file%'
            namer: vich_uploader.namer_uniqid
